apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: cassandra-storage-class
  gcePersistentDisk:
    fsType: ext4
    pdName: cassandra-disk 
