apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cassandra-storage-class
  resources:
    requests:
      storage: 200Gi
